export const GET_COUNTRY = 'GET_COUNTRY'
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY'
export const GET_DETAIL = 'GET_DETAIL'
export const FILTER_CONTINENT = 'FILTER_CONTINENT'
export const FILTER_ORDER = 'FILTER_ORDER'
export const GET_ACTIVITY = 'GET_ACTIVITY'
export const FILTER_ACTIVITY = 'FILTER_ACTIVITY'
export const POST_ACTIVITY = 'POST_ACTIVITY'


